function testBSON
%TESTBSON

  fixtures = {...
    1, ...
    int32(1), ...
    int64(1), ...
    true, ...
    'foo', ...
    uint8(1:5), ...
    1:5, ...
    int32(1:5), ...
    int64(1:5), ...
    true(1, 4), ...
    {1, true, 'foo'}, ...
    struct('a', 1, 'b', 2, 'c', 3), ...
    repmat(cat(3, magic(4), zeros(4)), [1,1,1,2]), ...
    repmat(struct('a', 1, 'b', 2, 'c', 3), [1,1,1,2]), ...
    {{{1,2},{3,4}},{{5,6},{7,8}}} ...
  };
  for i = 1:numel(fixtures)
    value1 = fixtures{i};
    bson = ejdb.encodeBSON(value1);
    value2 = ejdb.decodeBSON(bson);
    disp(value1);
    disp(value2);
  end

end